version: '3.4'

networks:
  public:
    external: true


services:
  traefik:
    image: traefik:v2.4
    networks:
      public:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.network=public
      - --providers.docker.swarmmode
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=$EMAIL
      - --certificatesresolvers.le.acme.dnschallenge.provider=namecheap
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
#      - --certificatesresolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
#      - --log.level=DEBUG
    environment:
      NAMECHEAP_API_USER: $NAMECHEAP_API_USER
      NAMECHEAP_API_KEY: $NAMECHEAP_API_KEY
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=false
