version: '3.4'
networks:
  public:
    external: true

services:
  home:
    image: iotresister/test
    networks:
      - public
    deploy:
      replicas: 3
      update_config:
        delay: 5s
        parallelism: 2
        failure_action: rollback
      labels:
        - traefik.enable=true
        - traefik.http.routers.home.service=home
        - traefik.http.routers.home.entrypoints=web
        - traefik.http.routers.home.rule=Host(`$DOMAIN`)
        - traefik.http.services.home.loadbalancer.server.port=80
