version: '3.4'
networks:
  public:
    external: true


services:
  wiki:
    image: sway/wiki
    environment:
      DB_SERVER: mariadb
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $WIKI_DB
    deploy:
      labels:
        - traefik.http.routers.wiki.rule=Host(`wiki.beta.$DOMAIN`)
        - traefik.http.routers.wiki.entrypoints=websecure
        - traefik.http.routers.wiki.tls.certresolver=le
      replicas: 3
      update_config:
        delay: 5s
        parallelism: 2
        failure_action: rollback
    networks:
      - public
