version: '3.4'
networks:
  public:
    external: true


services:
  wiki:
    image: swayme/wiki
    environment:
      DB_SERVER: '10.3.4.182'
      DB_PASSWORD: $DB_PASSWORD
      DB_USER: $USERNAME
      DB_NAME: beta_wiki
      DEBUG: 'true'
    volumes:
      - ./LocalSettings_beta.php:/var/www/html/LocalSettings.php
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.http.routers.wiki.rule=Host(`wiki.beta.swayme.xyz`)
        - traefik.http.routers.wiki.entrypoints=websecure
        - traefik.http.routers.wiki.tls.certresolver=le
        - traefik.http.services.wiki.loadbalancer.server.port=80
#      replicas: 3
#      update_config:
#        delay: 5s
#        parallelism: 2
#        failure_action: rollback
    networks:
      - public
