version: '3.4'
networks:
  public:
    external: true

services:
  wiki:
    image: iotresister/test
    networks:
      - public
    deploy:
      replicas: 3
      update_config:
        delay: 5s
        parallelism: 2
        failure_action: rollback
      labels:
        - traefik.http.routers.wiki.entrypoints=websecure
        - traefik.http.routers.wiki.rule=Host(`wiki.$DOMAIN`)
        - traefik.http.services.wiki.loadbalancer.server.port=80 # https://tinyurl.com/tvfuay2n
        - traefik.http.routers.wiki.tls.certresolver=le
